### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by henning-roos** [eiffel-community/eiffel-store#6]
### Description
Add licence file. Use https://github.com/eiffel-community/eiffel-repository-template/blob/master/LICENSE

### Motivation
See https://github.com/eiffel-community/eiffel-repository-template/blob/master/CONTRIBUTING.md#license-management

**Comment by m-linner-ericsson** [comment]
In preparation to archive as decided in https://github.com/eiffel-community/eiffel-store/issues/10 this repo we will close all open issues

**Comment by m-linner-ericsson** [comment]
Wrong state, should have been closed as not planned.
